FROM ubuntu:latest
RUN apt-get update -y && apt-get upgrade -y


RUN apt-get install ssh=1:8.9p1-3 -y --no-install-recommends \
	&& apt-get clean


RUN apt-get install git=1:2.34.1-1ubuntu1.5 -y --no-install-recommends \
	&& apt-get clean


# Git Config
RUN git config --global user.name RonTamG \
	&& git config --global user.email 33351836+RonTamG@users.noreply.github.com


# Install code server
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get install curl=7.81.0-1ubuntu1.6 -y \
	&& curl -fsSL https://code-server.dev/install.sh | sh \
	&& apt-get remove curl -y \
	&& apt-get autoremove -y \
	&& apt-get clean


# Extensions
RUN code-server --install-extension akamud.vscode-theme-onedark@2.3.0 \
	&& code-server --install-extension mhutchie.git-graph@1.30.0 \
	&& code-server --install-extension PKief.material-icon-theme@4.22.0 \
	&& code-server --install-extension usernamehw.errorlens@3.6.0


# Neovim
RUN apt-get install neovim=0.6.1-3 -y --no-install-recommends \
	&& apt-get clean \
 	&& rm -rf /var/lib/apt/lists/* \
	&& code-server --install-extension asvetliakov.vscode-neovim@0.0.89 \
	&& code-server --install-extension vspacecode.whichkey@0.11.3


EXPOSE 8080


COPY ./init.vim /root/.config/nvim/init.vim
COPY ./keybindings.json /root/.local/share/code-server/User/keybindings.json
COPY ./settings.json /root/.local/share/code-server/User/settings.json


CMD ["code-server", \
	"--bind-addr", "0.0.0.0:8080", \
	"--auth", "none"]
