FROM debian:latest
RUN apt-get update -y && apt-get upgrade -y


RUN apt-get install ssh -y --no-install-recommends \
	&& apt-get clean


RUN apt-get install git -y --no-install-recommends \
	&& apt-get clean


# Git Config
RUN git config --global user.name RonTamG \
	&& git config --global user.email 33351836+RonTamG@users.noreply.github.com


# Install code server
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN apt-get install curl -y \
	&& curl -fsSL https://code-server.dev/install.sh | sh


# Extensions
RUN code-server --install-extension akamud.vscode-theme-onedark \
	&& code-server --install-extension mhutchie.git-graph \
	&& code-server --install-extension PKief.material-icon-theme \
	&& code-server --install-extension usernamehw.errorlens \
	&& code-server --install-extension ms-vscode.hexeditor


# Neovim
RUN curl -fsSL https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.deb -o /tmp/nvim-linux64.deb \
        && apt install /tmp/nvim-linux64.deb \
	&& rm /tmp/nvim-linux64.deb \
	&& apt-get remove curl -y \
	&& apt-get autoremove -y \
	&& apt-get clean \
	&& rm -rf /var/lib/apt/lists/*

RUN code-server --install-extension asvetliakov.vscode-neovim \
	&& code-server --install-extension vspacecode.whichkey \   


EXPOSE 8080


COPY ./init.vim /root/.config/nvim/init.vim
COPY ./keybindings.json /root/.local/share/code-server/User/keybindings.json
COPY ./settings.json /root/.local/share/code-server/User/settings.json


CMD ["code-server", \
	"--bind-addr", "0.0.0.0:8080", \
	"--auth", "none"]

